### ISSUE TITLE
NoReturn issue with registering a signal handler via lambda

### ISSUE THREAD

**Issue by timabbott** [python/mypy#2955]
This is a simplified example, which throws the following exception:
```
import signal
import sys
signal.signal(signal.SIGTERM, lambda signum, stack: sys.exit(1))
```

`/tmp/foo.py:3: error: Argument 2 to "signal" has incompatible type Callable[[Signals, FrameType], NoReturn]; expected "Union[Callable[[Signals, FrameType], None], int, Handlers]"`

**Comment by ilevkivskyi** [comment]
The "workaround" is to use the ``--strict-optional`` flag. Anyway, there is a plan to turn on this flag by default in one of the future releases.

**Comment by JelleZijlstra** [comment]
This is probably an issue with the typeshed stub for `signal.signal`, which requires the handler to return None (https://github.com/python/typeshed/blob/master/stdlib/3/signal.pyi). It should perhaps allow returning Any, or `Union[None, NoReturn]`. See also https://github.com/python/typing/pull/397 where I foolishly said just now that I couldn't think of a use case for a callback returning NoReturn.

@ilevkivskyi I'm not sure how strict-optional relates to this problem.

**Comment by ilevkivskyi** [comment]
> I'm not sure how strict-optional relates to this problem

I think, it is. Because there is no such thing as ``NoReturn`` internally, it is just an ``UninhabitedType`` with a special flag. And, strictly speaking, ``UninhabitedType`` is a subtype of ``NoneTyp``. Somehow, this is treated correctly with ``--strict-optional`` (as it also happens in some other cases involving ``None``). On the contrary, without ``--strict-optional`` mypy treats ``NoneTyp`` vs ``Void`` vs ``UninhabitedType`` in somewhat opaque way.

**Comment by gvanrossum** [comment]
Thanks for reporting! `NoReturn` may not be experimental but it's new in this release...

**Comment by ddfisher** [comment]
I'm working on bringing the typechecking improvements of strict None checking to mypy without having to turn strict None checking on -- I think that should fix this issue.

**Comment by gvanrossum** [comment]
So, concluding, do we need to support `Union[X, NoReturn]` or not?

**Comment by ilevkivskyi** [comment]
I think that we should support this in the sense that ``Union[X, NoReturn] == X`` (``NoReturn`` is basically a bottom type). This already works for most ``X`` except for ``None``. And this is what @ddfisher is working on. So that I think no _additional_ actions are needed here.

**Comment by ddfisher** [comment]
Agreed.

(And update on timeline for fix: was just sick for a week, so should be a few days from _now_.)

**Comment by xylix** [comment]
What's the progress with this? I'm still getting the original described error when using lambdas with singla handler registration.

**Comment by erictraut** [comment]
I think this may have been fixed at some point. The latest version of mypy no longer emits an error for this code sample.
